version: "3.5"

services:
  gaze-point-prediction:
    build: gaze_point
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ipc: host
    networks:
      - proxynet
    ports:
      - "5555:5555"

  gaze-object:
      build: gaze_object
      ipc: host
      networks:
        - proxynet


  video-acq:
    build: video_acq
    devices:
      - /dev/video0:/dev/video0
    networks:
      - proxynet
    ports:
      - "5556:5556"

  yolo-service:
    build: yolo_service
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ipc: host
    networks:
      - proxynet
    ports:
      - "5557:5557"

  gaze-client:
    build: gaze_client
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ipc: host
    networks:
      - proxynet


networks:
  proxynet:
    name: gaze_services_network

