version: "3.5"

services:
  gaze-point-prediction:
    build:
      context: gaze_point
      dockerfile: Dockerfile.nano
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ipc: host
    networks:
      - proxynet
    ports:
      - "5555:5555"

  gaze-object:
    build: gaze_object
    ipc: host
    networks:
      - proxynet

  save-results-usb:
    build: save_results_usb
    volumes:
      - /media/${USER}:/storage/
    #privileged: true
    networks:
      - proxynet

  video-acq:
    build: nano_vid_acq
    networks:
      - proxynet
    ports:
      - "5556:5556"

  yolo-service:
    build:
      context: yolo_service
      dockerfile: Dockerfile.nano
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ipc: host
    networks:
      - proxynet
    ports:
      - "5557:5557"

  gaze-client:
    build: gaze_client
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ipc: host
    networks:
      - proxynet

networks:
  proxynet:
    name: gaze_services_network